/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.aerodeskpro.gui;

import com.formdev.flatlaf.FlatLightLaf;
import dev.aerodeskpro.validation.Validator;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.DriverManager;


import dev.aerodeskpro.validation.Validator;




/**
 *
 * @author Dell
 */
public class PlaneRegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form PlaneRegisterForm
     */
    public PlaneRegisterForm() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Plane Register Form");

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAirportId = new javax.swing.JTextField();
        txtPlaneNo = new javax.swing.JTextField();
        txtPlaneModel = new javax.swing.JTextField();
        txtSeatCapacity = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        txtRegisterNo = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        txtBuiltYear = new javax.swing.JFormattedTextField();
        roundedButton1 = new dev.aerodeskpro.components.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 62, 200));
        jLabel1.setText("Airport ID");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 62, 200));
        jLabel2.setText("Plane No");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 62, 200));
        jLabel3.setText("Plane Model");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 62, 200));
        jLabel4.setText("Seat Capacity");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 62, 200));
        jLabel5.setText("Manufacturer");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(62, 62, 200));
        jLabel6.setText("Built Year");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(62, 62, 200));
        jLabel7.setText("Register No");

        txtAirportId.setBackground(new java.awt.Color(204, 204, 204));
        txtAirportId.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N

        txtPlaneNo.setBackground(new java.awt.Color(204, 204, 204));
        txtPlaneNo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N

        txtPlaneModel.setBackground(new java.awt.Color(204, 204, 204));
        txtPlaneModel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N

        txtSeatCapacity.setBackground(new java.awt.Color(204, 204, 204));
        txtSeatCapacity.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N

        txtManufacturer.setBackground(new java.awt.Color(204, 204, 204));
        txtManufacturer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N

        txtRegisterNo.setBackground(new java.awt.Color(204, 204, 204));
        txtRegisterNo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N

        btnRegister.setBackground(new java.awt.Color(62, 62, 200));
        btnRegister.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Submit");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        try {
            txtBuiltYear.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        roundedButton1.setText("Back  To Dashboard");
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(84, 84, 84)
                        .addComponent(txtAirportId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(89, 89, 89)
                        .addComponent(txtPlaneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addGap(66, 66, 66)
                        .addComponent(txtPlaneModel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62)
                        .addComponent(txtSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addGap(60, 60, 60)
                        .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegisterNo)
                            .addComponent(txtBuiltYear, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtAirportId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPlaneModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuiltYear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtRegisterNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        registerPlane();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_roundedButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaneRegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private dev.aerodeskpro.components.RoundedButton roundedButton1;
    private javax.swing.JTextField txtAirportId;
    private javax.swing.JFormattedTextField txtBuiltYear;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtPlaneModel;
    private javax.swing.JTextField txtPlaneNo;
    private javax.swing.JTextField txtRegisterNo;
    private javax.swing.JTextField txtSeatCapacity;
    // End of variables declaration//GEN-END:variables

    private void registerPlane()  {
       
              // int id=Integer.parseInt(txtAirportId.getText());
               //int plane_no=Integer.parseInt(txtPlaneNo.getText());
    int id = 0;
    int plane_no = 0;

    // Handle number format exceptions FIRST
    try {
        id = Integer.parseInt(txtAirportId.getText().trim());
        plane_no = Integer.parseInt(txtPlaneNo.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Airport ID and Plane Number must be valid integers.",
                "Input Error",
                JOptionPane.WARNING_MESSAGE);
        return; // Exit early if invalid
    }

       
               String model=txtPlaneModel.getText();
               String capcity=txtSeatCapacity.getText();
               String manufacture=txtManufacturer.getText();
               String builder=txtBuiltYear.getText();
               String register=txtRegisterNo.getText();
               if(!Validator.isSelectedItemValid(id)){
               return;
               } else if(!Validator.isSelectedItemValid(plane_no)){
               return;
               }else if(!Validator.isInputFieldValid(model)){
               return;
               }else if(!Validator.isInputFieldValid(capcity)){
               return;
               }else if(!Validator.isInputFieldValid(manufacture)){
               return;
               }else if(!Validator.isInputFieldValid(builder)){
               return;
               }else if(!Validator.isInputFieldValid(register)){
               return;
               }
               try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/flight_schedular","root","Dolphin#2004");
            Statement s=c.createStatement();
          
            ResultSet rs;
           
            s.execute("INSERT INTO `registration`(`id`,`plane_no`,`model`,`capcity`,`manufacture`,`builder`,`register`) "
                    + "VALUES('"+id+"','"+plane_no+"','"+model+"','"+capcity+"','"+manufacture+"','"+builder+"','"+register+"')");
           JOptionPane.showMessageDialog(null, "Data Load Successfully");
               }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Input valid Id","warning",JOptionPane.WARNING_MESSAGE);
               
               
               }catch(SQLException |ClassNotFoundException e){
               e.printStackTrace();
               
               }
       
    }
}
